"""add Department

Revision ID: 662adf4ac08e
Revises: 3b744ce7e1f4
Create Date: 2024-08-25 15:39:44.675389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662adf4ac08e'
down_revision = '3b744ce7e1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
